[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
logfile_maxbytes=10MB
loglevel=info

[program:fastapi]
command=uvicorn backend.app:app --host 0.0.0.0 --port 8000
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/fastapi.log
stderr_logfile=/var/log/fastapi_err.log
stdout_logfile_maxbytes=5MB
stderr_logfile_maxbytes=5MB

[program:streamlit]
command=streamlit run frontend/frontend.py --server.port=8501 --server.address=0.0.0.0 --server.headless=true
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/streamlit.log
stderr_logfile=/var/log/streamlit_err.log
stdout_logfile_maxbytes=5MB
stderr_logfile_maxbytes=5MB